# Generated by Django 5.0.6 on 2024-06-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_img', models.ImageField(upload_to='image/')),
                ('auther', models.CharField(max_length=20)),
                ('book_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=40)),
                ('available_copies', models.IntegerField()),
            ],
        ),
    ]
