# Generated by Django 5.0.6 on 2024-06-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_acceptedbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedbooks',
            name='request_date',
        ),
    ]
