# Generated by Django 5.0.6 on 2024-06-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_remove_acceptedbooks_book_remove_acceptedbooks_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBooksNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('auther', models.CharField(max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('fine', models.IntegerField(default=0)),
                ('userd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.userdetails')),
            ],
        ),
    ]
