# Generated by Django 5.0.6 on 2024-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_acceptedbooksnewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedbooksnewmodel',
            name='book_img',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
