# Generated by Django 5.0.6 on 2024-06-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_acceptedbooksnewmodel_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedbooksnewmodel',
            name='book_img',
        ),
    ]
